name: Deploy to PyPI

on:
  release:
    types: [published]
  push:
    branches: [main, develop]

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install cibuildwheel
      run: python3 -m pip install cibuildwheel

    - name: Build wheels
      run: python3 -m cibuildwheel --output-dir dist
      env:
        CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
        CIBW_SKIP: "pp*"
        CIBW_ARCHS: "auto64"

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}
        path: dist/

  deploy:
    needs: build-wheels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: dist/

    - run: python3 -m pip install --upgrade twine
    - run: twine upload dist/**/*.whl dist/**/*.tar.gz
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}